### ISSUE TITLE
Animating text character by character

### ISSUE THREAD

**Issue by appcessorize** [yapstudios/YapAnimator#4]
How can I animate text character by character with this library

**Comment by olliewagner** [comment]
There are a bunch of ways that I could think of to animate text in one letter at a time — how you'd do it would depend on the effect of course. Let's say you want to animate text in a sort of typewriter effect: 

1. Create an array containing each character of your string
2. Create a `YapAnimator<Double>` that you'll use to toggle from `0` to `1`
3. The animator's `eachFrame` closure would take the value (ranging from 0 to 1) and re-map it to the number of characters in your array.
4. Create a string from your array (up to the index of the remapped value) and apply it to your label.

Now you can simply set the animator to 0 or 1 (or any value in between) and have the text transition in or out. 

Ultimately, the best way of using YapAnimator is to think, "How can I control `yourproblemhere` with a number". Sometimes it is very direct (like setting opacity), but often times the more creative use cases will involve mapping/interpolating to something else.
