### ISSUE TITLE
NSColor.ColorType build error on macOS with Swift 4

### ISSUE THREAD

**Issue by dnsmob** [yapstudios/YapAnimator#9]
Base SDK 10.13 ~~ no other available
Target 10.12 ~~ changing target to anything else (including 10.13) does not seem to make a difference.

On YapAnimator | Animatable.swift at build-time
line 236: `guard let ci = CIColor(color: self) else { return Array<Double>(repeating: 0, count: type(of:self).count) }` **type** seems to be at fault. `Cannot call value of non-function type 'NSColor.ColorType'`

Any ideas?

**Comment by ArthurXu424** [comment]
Yeah, I got same error

**Comment by olliewagner** [comment]
Fixed!
